---
output: html_document
---
<br>

## **[datadavidz] blog**

<br><br>

### **Tidy Tuesday: Steam Games**
*Posted on March 16, 2021*

Question addressed: What was the impact of the US Covid-19 lockdown on the top Steam games?  
Visualization: A stacked, ridgeline plot for the top 5 games with overlapping game titles. 

[Full post](2021-03-16_tt_SteamGames.html)

***

### **Tidy Tuesday: Bechdel Test for Movies**
*Posted on March 9, 2021*

Question addressed: Is there any correlation between Bechdel test result and profitability of big budget movies?  
Visualization: A bump chart with labels indicating movie titles. 

[Full post](2021-03-09_tt_BechdelMovies.html)

***

### **Tidy Tuesday: Superbowl Commercials**
*Posted on March 2, 2021*

Question addressed: What were the most common elements in Superbowl commercials for top 10 brands 2000-2020?  
Visualization: Create an infographic-style figure combining doughnut-style charts and images. 

[Full post](2021-03-02_tt_Superbowl.html)

***

### **Tidy Tuesday: Employment and Earnings**
*Posted on February 23, 2021*

Question addressed: What occupations within the Manufacturing sector saw the largest employment decline in 2020?  
Visualization: Create a lollipop chart for different industries and size them proportional to the employment numbers. 

[Full post](2021-02-23_tt_Employment.html)

***

### **Tidy Tuesday: W.E.B. Du Bois Challenge**
*Posted on February 16, 2021*

Question addressed: Can I accurately reproduce a W.E.B Du Bois figure?  
Visualization: Re-created a unique chart which included a spiral and custom font.  

[Full post](2021-02-16_tt_WEBDubois.html)

***

### **Tidy Tuesday: Student Loan Debt and Income by Race Dataset**
*Posted on February 9, 2021*

Question addressed: How did average student loan debt-to-income change over time by race?  
Visualization: Created a clean and simple line chart.  

[Full post](2021-02-09_tt_LoanDebtIncome.html)

***

### **Tidy Tuesday: HBCU Enrollments Dataset**
*Posted on February 2, 2021*

Question addressed: How did HBCU enrollments changes between 1990s and 2000s?  
Visualization: Created a waffle plot visualization using waffle package.  

[Full post](2021-02-02_tt_HBCUWaffle.html)

***

### **Tidy Tuesday: Break Free From Plastics Dataset**
*Posted on January 26, 2021*

Question addressed: What were the top 10 countries participating in Break Free From Plastics events?  
Visualization: Created a bar chart visualization using ggthemes package.  

[Full post](2021-01-26_tt_PlasticWaste.html)

***

### **Concrete Dataset Part 8: Comparison of Predictive Models for Concrete Compressive Strength**
*Posted on December 4, 2020*

The predictive accuracy of the final models build on the Concrete dataset are compared.  The random forest and xgboost models gave the best predictive performance.  The prediction time for these two models was significantly longer than the conventional modeling approach but the difference was not of practical importance for this example.  Over 10,000 predictions can be perfomed using the xgboost model in less than a second using a standard desktop computer.

[Full post](2020-12-04_ConcreteSummary.html)

***

### **Concrete Dataset Part 7: Random Forest Model using ranger**
*Posted on December 4, 2020*

A random forest model is fit to predict the compressive strength of concrete formulation using a tidymodels approach.  The random forest model showed similar performance to the XGBoost model only slightly worse.

[Full post](2020-12-04_ConcreteRF.html)

***

### **Concrete Dataset Part 6: Extreme Gradient Boosted Tree Model using XGboost**
*Posted on December 3, 2020*

A boosted tree model is fit to predict the compressive strength of concrete formulation using a tidymodels approach.  The XGBoost model showed the best performance of the predictive models so far.

[Full post](2020-12-03_ConcreteXGB.html)

***

### **Concrete Dataset Part 5: Single-Layer Neural Network Model using nnet**
*Posted on December 2, 2020*

A simple neural network is fit to predict the compressive strength of concrete formulation using a tidymodels approach.  This single-layer neural network showed significantly better performance than both the conventional model and the GLMnet model.

[Full post](2020-12-02_ConcreteMLP.html)

***

### **Concrete Dataset Part 4: Conventional Material Model using nls**
*Posted on June 16, 2020*

The performance of a conventional model is assessed by optimizing parameters for a given transfer function using the nls package.

[Full post](2020-06-16_ConcreteNLS.html)

***

### **Concrete Dataset Part 3: Predictive Modeling using GLMnet**
*Posted on March 26, 2020*

A model to predict the compressive strength of different concrete formulations is built using GLMnet.  A tidymodels approach is used to build and analyze the predictive model.

[Full post](2020-03-26_ConcreteGLM.html)

***

### **Concrete Dataset Part 2: Exploratory Data Analysis**
*Posted on March 17, 2020*

In this post, I use several EDA tools to analyze the Concrete dataset.  More specifically, the distributions of the variables and correlations between the variables are explored using packages such as skimr, GGally and correlationfunnel.

[Full post](2020-03-17_ConcreteEDA.html)

***

### **Concrete Dataset Part 1: Introduction**
*Posted on February 14, 2020*

A brief introduction to the Concrete dataset available on the UCI repository.  This dataset is interesting for those persons interested in predicting material properties from formulations.

[Full post](2020-02-14_ConcreteIntro.html)

***

### **Monster Hunting Part 2: Guild Gifts**
*Posted on March 27, 2019*

In this post, I examine the potential daily rewards obtained from guild gifts.  As you will see, in a full and active guild, the rewards obtained from guild gifts can easily dwarf the rewards obtained from your personal monster hunting.

[Full post](2019-03-27_MhuntPart2.html)

***

### **Monster Hunting Part 1: Personal Loot**
*Posted on March 13, 2019*

One of the long running debates in my Lords Mobile guild has been how to best benefit the entire guild when monster hunting.  In this post, I look at the average personal loot you would expect from using all of your daily energy to hunt a specific level of monster.

[Full post](2019-03-13_MhuntPart1.html)

***

### **Was I fooled by the Trickstar?**
*Posted on February 27, 2019*

A recent event in Lords Mobile for Valentine's day was a Trickstar monster kill.  The Trickstar looks like an evil version of Cupid so I suppose it was an appropriate way to celebrate the holiday.  This post calculates the drop rate for the different holy star rewards and analyzes whether there was any significant dependency between the previous and next reward.

[Full post](2019-02-27_Trickstar.html)

***

### **What's the trouble, yo?  It's a troubledough!**
*Posted on February 13, 2019*

A recent event in the Lords Mobile game was a monster hunting event with a new type of monster: the Troubledough.  The event was concurrent with the release of new background music for the game.  Slaying the troubledoughs rewards the player with a "Chest of Echoes".  This post analyzes the chest rewards.  Were the rewards worth the effort?

[Full post](2019-02-13_Troubledough.html)

***
<!--- put in r chunk to float an image to the right.
out.extra='style="float:right; padding:10px"'
--->

### **What is Lords Mobile?**
*Posted on January 30, 2019*

In this post, I provide a brief introduction to Lords Mobile game.  I take various aspects of the gameplay in Lords Mobile as a source for discussions in many of my posts.  The purpose of this post is to give readers an overview for those who are unfamiliar with the game.  Perhaps, you will want to join and build your own kingdom?


[Full post](2019-01-30_LordsOverview.html)


